#! /bin/sh

# User variables
rm3_ifttt_path="/insert/path/to/repository/here/run.py"
rm3_ifttt_port=1234

case "$1" in
  start)
    echo "Starting example"
    # run application you want to start
    python $rm3_ifttt_path $rm3_ifttt_port &
    ;;
  stop)
    echo "Stopping example"
    # kill application you want to stop
    killall python
    ;;
  *)
    echo "Usage: /etc/init.d/example{start|stop}"
    exit 1
    ;;
esac

exit 0
